layout_spectrum: 0.9586466
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5300752
  brandStrength: 1
  lightness: 0.3818474
  brandColors:
    - '#211112'
    - '#205EFF'
    - '#5D9FFF'
    - '#FFFFFF'
    - '#C1C177'
  rhythmicContrast: 0.490333
typography_spectrum: 0.4706
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thinking
