favicon: null
name: thinking
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4505908
  brandStrength: 0.5193341
  lightness: 0.4914071
  brandColors:
    - '#0147FF'
    - '#18171C'
    - '#705E47'
    - '#CDB392'
    - '#5699FF'
  rhythmicContrast: 0.5547798
typography_spectrum: 0.8974221
layout_spectrum: 0.2937701
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
