favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5300752
  brandStrength: 0.1831364
  rhythmicContrast: 0.490333
  brandColors:
    - '#211112'
    - '#205EFF'
    - '#5D9FFF'
    - '#FFFFFF'
    - '#C1C177'
  lightness: 0.3818474
typography_spectrum: 0.8974221
layout_spectrum: 0.7620838
analytics:
  twitter: null
  google: null
  facebook: null
name: thinking
