typography_spectrum: 0.5257788
color:
  saturation: 0.4505908
  brandStrength: 0.5118152
  lightness: 0.4914071
  brandColors:
    - '#2E0F0C'
    - '#E2EDEF'
    - '#3C891B'
    - '#2DC0E4'
    - '#DF4A45'
  rhythmicContrast: 0.5547798
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3378088
analytics:
  twitter: null
  google: null
  facebook: null
name: thinking
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Colourful
    id: 96e6ea7a-54f4-4088-93c0-273daacbb0af
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Sharing Random Thoughts while Testing AI
purpose: []
