name: thinking
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9414608
  brandStrength: 0.8179377
  lightness: 0.9307196
  brandColors:
    - '#0147FF'
    - '#18171C'
    - '#705E47'
    - '#CDB392'
    - '#5699FF'
  rhythmicContrast: 0.8694951
typography_spectrum: 0.8974221
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.896348
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
